"use client";
import {useState} from 'react';
import {ArrowUpRight,ChevronDown,Ruler,Activity,Timer,Users} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {historySummary,usableStats} from '@/lib/model';
import {COMBAT_METRICS,statLeader} from '@/lib/matchup';
import type {Fighter,Event,Fight,PastFight} from '@/lib/types';
import {formatHeight,formatReach} from '@/lib/measurements';
type Row={id:string;label:string;values:[string,string];raw?:[number|undefined,number|undefined];lower?:boolean;compare?:boolean;note:string};
const n=(v:number|undefined,unit='')=>v===undefined||!Number.isFinite(v)?'—':`${v}${unit}`;
export function ArenaStats({a,b,event,fight,onEdit}:{a:Fighter;b:Fighter;event:Event;fight:Fight;onEdit?:(f:Fighter)=>void}){
 const [expanded,setExpanded]=useState<string|null>(null),[differences,setDifferences]=useState(false);
 const aa=usableStats(a,event.date,fight.rules),bb=usableStats(b,event.date,fight.rules);
 const age=(f:Fighter)=>f.birthDate?Math.floor((Date.parse(event.date)-Date.parse(f.birthDate))/31557600000):f.age;
 const tape:Row[]=[{id:'height',label:'Height',values:[formatHeight(a.height),formatHeight(b.height)],note:'Listed height. Taller is not automatically better.'},{id:'reach',label:'Reach',values:[formatReach(a.reach),formatReach(b.reach)],raw:[a.reach,b.reach],compare:true,note:'Longer reach can help control range. Footwork and timing still matter.'},{id:'age',label:'Age at fight',values:[n(age(a)),n(age(b))],note:'Calculated from the listed birth date when available; otherwise the source’s listed age. Not an automatic advantage.'},{id:'stance',label:'Stance',values:[a.stance||'—',b.stance||'—'],note:'Listed stance. Fighters may switch during a bout.'},{id:'style',label:'Style',values:[a.style||'Not listed',b.style||'Not listed'],note:'A profile label does not measure how a fighter handles this opponent.'}];
 function rows(group:'striking'|'grappling'):Row[]{return COMBAT_METRICS.filter(r=>r.group===group).map(r=>({id:r.key,label:r.label,values:[n(aa?.[r.key] as number|undefined,` ${r.unit}`),n(bb?.[r.key] as number|undefined,` ${r.unit}`)],raw:[aa?.[r.key] as number|undefined,bb?.[r.key] as number|undefined],lower:r.lower,compare:true,note:r.context||`${r.lower?'Lower':'Higher'} is favourable for this metric. Career UFC averages, not last-10 figures.`}));}
 function comparison(data:Row[]){const shown=data.filter(r=>!differences||r.compare&&r.raw&&statLeader(...r.raw,r.lower));return <div className="arena-stat-rows">{shown.map(r=>{const leader=r.compare&&r.raw?statLeader(...r.raw,r.lower):null;return <div key={r.id} className={'arena-stat-row '+(expanded===r.id?'expanded':'')}><div className="arena-stat-line"><strong className={leader==='a'?'stat-better':''}>{r.values[0]}{leader==='a'&&<small>EDGE</small>}</strong><button type="button" onClick={()=>setExpanded(expanded===r.id?null:r.id)} aria-expanded={expanded===r.id} aria-controls={'explain-'+r.id}>{r.label}<ChevronDown size={14}/></button><strong className={leader==='b'?'stat-better':''}>{r.values[1]}{leader==='b'&&<small>EDGE</small>}</strong></div>{expanded===r.id&&<p id={'explain-'+r.id} className="arena-stat-explanation">{r.note}</p>}</div>})}{!shown.length&&<p className="arena-stats-empty">No verified differences in this category. Turn off “Edges only” to see all values.</p>}</div>}
 return <section className="arena-stats" aria-label="Compare the fighters"><Tabs defaultValue="tape" onValueChange={()=>{setExpanded(null);setDifferences(false)}}><div className="arena-stats-toolbar"><TabsList className="arena-stat-tabs"><TabsTrigger value="tape"><Ruler size={16}/>Profile</TabsTrigger><TabsTrigger value="striking"><Activity size={16}/>Striking</TabsTrigger>{fight.rules==='MMA'&&<TabsTrigger value="grappling"><Users size={16}/>Grappling</TabsTrigger>}<TabsTrigger value="form"><Timer size={16}/>Recent fights</TabsTrigger></TabsList></div><div className="arena-stat-names"><span>{a.name}</span><span>COMPARE</span><span>{b.name}</span></div><TabsContent value="tape"><div className="arena-stat-options"><span>Height in feet and inches · reach in inches</span></div>{comparison(tape)}{onEdit&&<div className="arena-profile-actions">{[a,b].map(f=><Button key={f.id} variant="ghost" onClick={()=>onEdit(f)}>Edit {f.name.split(' ')[0]}’s profile <ArrowUpRight size={14}/></Button>)}</div>}</TabsContent>{(['striking','grappling'] as const).filter(g=>g==='striking'||fight.rules==='MMA').map(g=><TabsContent key={g} value={g}><div className="arena-stat-options"><span>Career UFC averages</span><label><Switch checked={differences} onCheckedChange={setDifferences} aria-label="Show only verified statistical advantages"/>Edges only</label></div>{!aa&&!bb?<p className="arena-stats-empty">Detailed {g} averages aren’t available for this matchup. Profile and recent fights still show the sourced comparisons.</p>:comparison(rows(g))}<div className="arena-stat-sources">{[aa,bb].map((s,i)=>s&&<a key={i} href={s.source} target="_blank" rel="noopener noreferrer">{[a,b][i].name} · {s.asOf} <ArrowUpRight size={13}/></a>)}</div></TabsContent>)}<TabsContent value="form"><div className="arena-recent-grid">{[a,b].map(f=><RecentFighter key={f.id} f={f} event={event} fight={fight}/>)}</div></TabsContent></Tabs></section>;
}
function RecentFighter({f,event,fight}:{f:Fighter;event:Event;fight:Fight}){
 const h=historySummary(f,event.date,fight.rules),[chosen,setChosen]=useState<PastFight|null>(null);
 return <div className="arena-recent"><div className="arena-form-heading"><strong>{h.recent.length?h.record:'No history'}</strong><span>Last {h.recent.length} · newest first</span></div><div className="arena-form-buttons">{h.recent.map((x,i)=><button key={i} type="button" className={'result '+x.result.toLowerCase()+(chosen===x?' chosen':'')} onClick={()=>setChosen(chosen===x?null:x)} aria-pressed={chosen===x} aria-label={`${x.result} against ${x.opponent}, ${x.date}. Show bout details`}>{x.result}</button>)}</div>{chosen?<div className="arena-bout-insight"><strong>{chosen.opponent}</strong><span>{chosen.method} · {chosen.round?'Round '+chosen.round:'Round unknown'}</span><span>{chosen.date} · {chosen.promotion}</span><span>Opponent record: {chosen.opponentRecord||'Unverified'}</span>{chosen.source&&<a href={chosen.source} target="_blank" rel="noopener noreferrer">Bout source <ArrowUpRight size={13}/></a>}</div>:<p className="arena-form-hint">{h.recent.length?'Tap a result to inspect the opponent and finish.':'No verified history loaded.'}</p>}<p className="arena-form-rest">{h.layoff===null?'Layoff unknown':h.layoff+' days since last fight'}</p></div>;
}
