"use client";
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {RoundsPrediction} from '@/lib/rounds';
export function DurationEvidence({prediction:r,promotion}:{prediction:RoundsPrediction;promotion:string}){
 const [scope,setScope]=useState('all');
 return <details className="duration-evidence"><summary>Inspect both fighters’ last 10 durations</summary><p className="fine">Each result is tested against this fight’s {r.line}-round line. Only bouts before the event, under the same rules, are included.</p><Tabs value={scope} onValueChange={setScope}><TabsList><TabsTrigger value="all">All last 10</TabsTrigger><TabsTrigger value="same">{promotion} only</TabsTrigger><TabsTrigger value="other">Other promotions</TabsTrigger></TabsList></Tabs><div className="duration-columns">{r.durationEvidence.map(s=>{const rows=s.rows.filter(h=>scope==='all'||(scope==='same'?h.promotion===promotion:h.promotion!==promotion));const known=rows.filter(h=>h.side==='Over'||h.side==='Under');return <section key={s.id}><h5>{s.name}</h5><p><b>{known.filter(h=>h.side==='Over').length} over</b> · {known.filter(h=>h.side==='Under').length} under <span className="fine">· {rows.length-known.length} exact / unknown</span></p>{rows.length?<Table><TableHeader><TableRow><TableHead>Opponent / level</TableHead><TableHead>Finish</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{rows.map((h,i)=><TableRow key={i}><TableCell><strong>{h.opponent}</strong><small>{h.opponentRecord||'Record unknown'} · {h.promotion}</small><small>{h.date}</small></TableCell><TableCell><span className={'result '+h.result.toLowerCase()}>{h.result}</span> {h.method}<small>R{h.round??'?'} · {h.time??'Time unknown'}</small></TableCell><TableCell><span className={'duration-side '+(h.side?.toLowerCase()||'')}>{h.side||'Unknown'}</span>{h.source&&<a href={h.source} target="_blank" rel="noopener noreferrer" aria-label={`Source for ${h.opponent}`}> ↗</a>}</TableCell></TableRow>)}</TableBody></Table>:<p className="fine">No bouts in this part of the last-10 sample.</p>}</section>})}</div><p className="fine">Raw counts are not the forecast. Recency, opponent quality, promotion, weight class and the other fighter’s durability also matter. Historical promotion does not by itself establish opponent quality.</p></details>;
}
