"use client";
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Flag,UFCRecord,History} from './research';
import {historySummary,usableStats,recordAtEvent} from '@/lib/model';
import {COMBAT_METRICS} from '@/lib/matchup';
import {formatHeight,formatReach} from '@/lib/measurements';
import type {Event,Fight,Fighter} from '@/lib/types';
export function FighterDossier({f,event,fight,onEdit}:{f:Fighter;event:Event;fight:Fight;onEdit?:()=>void}){
 const h=historySummary(f,event.date,fight.rules),stats=usableStats(f,event.date,fight.rules);
 const age=f.birthDate?Math.floor((Date.parse(event.date)-Date.parse(f.birthDate))/31557600000):f.age;
 const facts=[['Height',f.height===undefined?'Unknown':formatHeight(f.height)],['Reach',f.reach===undefined?'Unknown':formatReach(f.reach)],['Age at event',age??'Unknown'],['Stance',f.stance||'Unverified'],['Style label',f.style||'Unverified'],['Since last fight',h.layoff===null?'Unknown':h.layoff+' days']];
 return <div className="fighter-dossier"><div className="dossier-banner"><div><span><Flag country={f.country}/> {f.country||'Country unverified'}</span><h2>{f.name}</h2><strong>{recordAtEvent(f,event.date,fight.rules)}</strong><UFCRecord f={f} date={event.date}/><p className="fine">{f.recordScope||'Professional MMA'} · checked {f.historyChecked||'date unknown'}</p></div>{f.image&&<img src={f.image} alt={f.name} onError={e=>{e.currentTarget.style.display='none'}}/>}</div><Tabs defaultValue="profile"><TabsList className="dossier-tabs"><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="stats">Combat stats</TabsTrigger><TabsTrigger value="history">Fight history</TabsTrigger></TabsList><TabsContent value="profile"><dl className="dossier-facts">{facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="dossier-form"><span>Last {h.recent.length} · newest first</span><div className="form-strip">{h.recent.map((row,i)=><span key={i} className={'result '+row.result.toLowerCase()} title={`${row.opponent} · ${row.method} · ${row.date}`}>{row.result}</span>)}</div></div><p className="fine">Portrait capture date: {f.imageDate||'unknown'}. Appearance and style labels are not measured athletic ability.</p>{f.recordNote&&<p className="fine">{f.recordNote}</p>}<div className="stat-sources">{f.sources.map((s,i)=><a key={i} className="out" href={s.url} target="_blank" rel="noopener noreferrer">{s.label} · {s.checked} ↗</a>)}</div>{onEdit&&<Button variant="outline" onClick={onEdit}>Edit sourced facts</Button>}</TabsContent><TabsContent value="stats">{stats?<><div className="dossier-facts">{COMBAT_METRICS.map(m=><div key={m.key}><span>{m.label}</span><strong>{stats[m.key]??'—'} <small>{stats[m.key]===undefined?'':m.unit}</small></strong><p className="fine">{m.lower?'Lower is better':'Activity / performance measure'}</p></div>)}</div><p className="fine">{stats.scope} · checked {stats.asOf}. Career aggregates, not last-10 figures. Missing values are not zero.</p><a className="out" href={stats.source} target="_blank" rel="noopener noreferrer">Official statistics ↗</a></>:<p>Comparable pre-event {fight.rules} statistics have not been verified.</p>}</TabsContent><TabsContent value="history"><History f={f} event={event} rules={fight.rules} onEdit={onEdit}/></TabsContent></Tabs></div>;
}
