"use client";
import {DurationEvidence} from './duration-evidence';
import { Timer } from 'lucide-react';
import { predictRounds } from '@/lib/rounds';
import type { Event,Fight,Fighter } from '@/lib/types';
export function RoundsPick({fight,a,b,event,compact=false}:{fight:Fight;a:Fighter;b:Fighter;event:Event;compact?:boolean}){
 const r=predictRounds(fight,a,b,event);if(!r)return <div className="rounds-pick"><strong>{fight.rounds}-round bout</strong><p>No standard 1.5 / 2.5 total applies to this format.</p></div>;
 if(compact)return <section className="rounds-summary surface" aria-label="Rounds prediction"><div className="rounds-compact"><div><span>Rounds pick</span><strong>{r.side} {r.line}</strong></div><div><span>{fight.rounds} scheduled rounds</span><strong>{r.confidence===null?"Low evidence":r.confidence+"% lean"}</strong></div></div><ul>{r.notes.slice(0,3).map((note,i)=><li key={i}>{note}</li>)}</ul></section>;
 const half=r.roundMinutes/2,clock=`${Math.floor(half)}:${String(Math.round(half%1*60)).padStart(2,'0')}`;
 return <section className="rounds-pick"><div className="rounds-pick-heading"><div><p className="eyebrow"><Timer size={14}/> ROUNDS PICK</p><h4>{r.side} {r.line} <span>rounds</span></h4></div><div><strong>{r.confidence===null?'Very low':r.confidence+'%'} <small>{r.confidence===null?'confidence':'model confidence'}</small></strong><span>{r.strength} · unvalidated</span></div></div><div className="rounds-timeline" role="img" aria-label={`${fight.rounds} scheduled rounds. ${r.side} ${r.line} rounds.`}>{Array.from({length:fight.rounds},(_,i)=><span key={i} aria-hidden="true">R{i+1}</span>)}<i style={{left:`${r.line/fight.rounds*100}%`}}/><div className={'rounds-zone '+r.side.toLowerCase()} style={r.side==='Over'?{left:`${r.line/fight.rounds*100}%`,right:0}:{left:0,width:`${r.line/fight.rounds*100}%`}}/></div><p className="rounds-cutoff">{fight.rounds} × {r.roundMinutes}-minute rounds · Cutoff: {clock} elapsed in round {Math.ceil(r.line)}</p><p className="rounds-meaning">{r.side==='Over'?'Fight continues beyond':'Fight ends before'} the cutoff.</p>{r.limited&&<p className="rounds-limited">{r.confidence===null?'Fallback guess — no usable duration history.':'Tentative guess — limited duration history.'}</p>}<ul>{r.notes.slice(0,3).map((n,i)=><li key={i}>{n}</li>)}</ul><DurationEvidence prediction={r} promotion={event.promotion}/><div className="stat-sources">{r.sample.map(s=>s.source&&<a className="out" key={s.id} href={s.source} target="_blank" rel="noopener noreferrer">{s.name} history ↗</a>)}</div></section>;
}
