// Official fight clips from promotion YouTube channels, loaded from data/clips.json.
// Every ID in that file must be verified against the source channel (YouTube oEmbed: public +
// embeddable) before it is added; `verifiedAt` records the check. Do not add unverified IDs.
//
// The loader below is deliberately tolerant: the catalog is generated by a separate job and can
// grow to a few hundred items, so missing or null fields fall back to safe defaults and malformed
// rows are dropped instead of breaking the page.
import RAW from "../data/clips.json";
import { SEED_FIGHTERS } from "./data";
import { DIVISIONS } from "./rankings";
import { slugsForName } from "./roster";

export type ClipFormat = "full-fight" | "ko-clip" | "sub-clip" | "finish-clip" | "highlights";
export type ClipTag = "title-fight" | "upset" | "fotn" | "classic" | "recent" | "women";
/** What a highlight reel or finish clip is about: knockouts, submissions, or both. */
export type ClipFocus = "ko" | "sub" | "mixed";

export type Clip = {
  id: string;
  title: string;
  channel: string;
  format: ClipFormat;
  /** [A, B] for a fight, [A] for a single-fighter highlight reel. */
  fighters: string[];
  winner: string | null;
  event: string;
  date: string | null;
  year: number | null;
  method: string | null;
  division: string | null;
  tags: ClipTag[];
  blurb: string;
  verifiedAt: string | null;
  width: number | null;
  height: number | null;
  /** Optional start offset in seconds. */
  start: number | null;
  /** Reels and finish clips: whether they show knockouts, submissions or a mix (null when unknown). */
  focus: ClipFocus | null;
};

export const CLIP_FORMATS: ClipFormat[] = ["full-fight", "ko-clip", "sub-clip", "finish-clip", "highlights"];
const TAGS: ClipTag[] = ["title-fight", "upset", "fotn", "classic", "recent", "women"];
const FOCUS: ClipFocus[] = ["ko", "sub", "mixed"];

export const FORMAT_LABEL: Record<ClipFormat, string> = {
  "full-fight": "Full fight",
  "ko-clip": "Knockout clip",
  "sub-clip": "Submission clip",
  "finish-clip": "Finish clip",
  highlights: "Highlights",
};

const CHANNEL_NAME: Record<string, string> = { ufcespanol: "UFC Español", "UFC Espanol": "UFC Español" };
/** Commentary language for non-English official channels (shown as a small chip). */
export function clipLanguage(c: { channel: string; title?: string }): string | null {
  if (/eurasia|russia/i.test(c.channel)) return "Russian commentary";
  if (/espa/i.test(c.channel)) return "Spanish commentary";
  if (/brasil/i.test(c.channel)) return "Portuguese commentary";
  if (/deutschland/i.test(c.channel)) return "German commentary";
  // UFC India posts many English-language uploads; only flag Hindi when the title says so.
  if (/india/i.test(c.channel) && /[\u0900-\u097F]|hindi/i.test(c.title ?? "")) return "Hindi commentary";
  return null;
}
export const TAG_LABEL: Record<ClipTag, string> = {
  "title-fight": "Title fight",
  upset: "Upset",
  fotn: "Fight of the Night",
  classic: "Classic",
  recent: "New",
  women: "Women's",
};

/** Compact tag labels for cards. */
export const TAG_SHORT: Record<ClipTag, string> = { ...TAG_LABEL, fotn: "FOTN" };

/* ---------- loading ---------- */

const str = (v: unknown): string => (typeof v === "string" ? v.trim() : "");
const strOrNull = (v: unknown): string | null => str(v) || null;
const numOrNull = (v: unknown): number | null => (typeof v === "number" && Number.isFinite(v) ? v : null);

function toClip(r: Record<string, unknown>): Clip | null {
  const id = str(r.id);
  if (!/^[\w-]{11}$/.test(id)) return null;
  const fighters = (Array.isArray(r.fighters) ? r.fighters : []).map(str).filter(Boolean).slice(0, 2);
  if (!fighters.length) return null;
  const rawFormat = str(r.format) as ClipFormat;
  const format: ClipFormat = CLIP_FORMATS.includes(rawFormat) ? rawFormat : fighters.length < 2 ? "highlights" : "finish-clip";
  const date = /^\d{4}-\d{2}-\d{2}$/.test(str(r.date)) ? str(r.date) : null;
  const year = numOrNull(r.year) ?? (date ? Number(date.slice(0, 4)) : null);
  const winner = strOrNull(r.winner);
  const tags = (Array.isArray(r.tags) ? r.tags : []).map(str).filter((t): t is ClipTag => (TAGS as string[]).includes(t));
  const rawFocus = str(r.focus) as ClipFocus;
  return {
    id,
    title: str(r.title) || fighters.join(" vs "),
    channel: CHANNEL_NAME[str(r.channel)] ?? (str(r.channel) || "UFC"),
    format,
    fighters,
    winner: winner && fighters.some((f) => normalizeClipName(f) === normalizeClipName(winner)) ? winner : null,
    event: str(r.event),
    date,
    year,
    method: strOrNull(r.method),
    division: strOrNull(r.division),
    tags: [...new Set(tags)],
    blurb: str(r.blurb),
    verifiedAt: strOrNull(r.verifiedAt),
    width: numOrNull(r.width),
    height: numOrNull(r.height),
    start: numOrNull(r.start),
    focus: FOCUS.includes(rawFocus) ? rawFocus : null,
  };
}

function loadClips(): Clip[] {
  const raw = RAW as unknown;
  const rows = Array.isArray(raw) ? raw : Array.isArray((raw as { clips?: unknown })?.clips) ? (raw as { clips: unknown[] }).clips : [];
  const seen = new Set<string>();
  const out: Clip[] = [];
  for (const r of rows) {
    if (!r || typeof r !== "object") continue;
    const c = toClip(r as Record<string, unknown>);
    if (!c || seen.has(c.id)) continue;
    seen.add(c.id);
    out.push(c);
  }
  return out;
}

export const CLIPS: Clip[] = loadClips();

/* ---------- names ---------- */

/** Lowercase, strip accents, drop "Jr." and punctuation, collapse spaces. */
export function normalizeClipName(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\b(jr|sr)\b\.?/g, " ")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const tokenSorted = (s: string) => normalizeClipName(s).split(" ").sort().join(" ");

function sameFighter(a: string, b: string): boolean {
  const na = normalizeClipName(a);
  return !!na && (na === normalizeClipName(b) || tokenSorted(a) === tokenSorted(b));
}

/** Clips featuring the fighter on either side (accent-, case-, word-order- and "Jr."-insensitive). */
export function clipsForFighter(name: string): Clip[] {
  if (!normalizeClipName(name)) return [];
  return CLIPS.filter((c) => c.fighters.some((f) => sameFighter(f, name)));
}

/** "Raul Rosas Jr." -> "Rosas Jr.", "Georges St-Pierre" -> "St-Pierre". */
export function clipSurname(name: string): string {
  const parts = name.trim().split(/\s+/);
  if (parts.length < 2) return name.trim();
  const last = parts[parts.length - 1];
  return /^(jr|sr|ii|iii|iv)\.?$/i.test(last) && parts.length > 2 ? `${parts[parts.length - 2]} ${last}` : last;
}

/** "Max Holloway" -> "MH", "Alatengheili" -> "AL". */
export function clipInitials(name: string): string {
  const parts = name
    .replace(/\b(jr|sr|ii|iii|iv)\b\.?/gi, "")
    .trim()
    .split(/[\s-]+/)
    .filter(Boolean);
  if (!parts.length) return "?";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

/* ---------- display helpers ---------- */

export const isReel = (c: Clip) => c.fighters.length < 2;

const KO_METHOD = /^T?KO\b/i;
const SUB_METHOD = /^(technical\s+)?submission\b/i;

/**
 * Belongs under Knockouts: knockout clips, knockout-focused reels and finish clips, and full fights
 * (or finish clips) whose official result is a KO/TKO.
 */
export function isKnockout(c: Clip): boolean {
  if (c.format === "ko-clip") return true;
  if (c.format === "sub-clip") return false;
  if ((c.format === "highlights" || c.format === "finish-clip") && c.focus === "ko") return true;
  return (c.format === "full-fight" || c.format === "finish-clip") && KO_METHOD.test(c.method ?? "");
}

/** Belongs under Submissions: the same rules as {@link isKnockout}, for submission finishes. */
export function isSubmission(c: Clip): boolean {
  if (c.format === "sub-clip") return true;
  if (c.format === "ko-clip") return false;
  if ((c.format === "highlights" || c.format === "finish-clip") && c.focus === "sub") return true;
  return (c.format === "full-fight" || c.format === "finish-clip") && SUB_METHOD.test(c.method ?? "");
}

/**
 * The card / hero label: "Full fight", "Knockout clip", "Submission clip", "Finish clip",
 * "Knockout highlights", "Submission highlights" or "Highlights". A full fight keeps "Full fight"
 * whatever its result, so the label never gives the finish away.
 */
export function clipLabel(c: Clip): string {
  if (c.format === "highlights") {
    if (c.focus === "ko") return "Knockout highlights";
    if (c.focus === "sub") return "Submission highlights";
    return FORMAT_LABEL.highlights;
  }
  if (c.format === "finish-clip") {
    if (c.focus === "ko" || KO_METHOD.test(c.method ?? "")) return FORMAT_LABEL["ko-clip"];
    if (c.focus === "sub" || SUB_METHOD.test(c.method ?? "")) return FORMAT_LABEL["sub-clip"];
  }
  return FORMAT_LABEL[c.format];
}

/** Colour family for a clip's label chip: knockout / submission reels borrow the clip colours. */
export function clipTone(c: Clip): ClipFormat {
  if (c.format === "highlights" || c.format === "finish-clip") {
    if (c.focus === "ko") return "ko-clip";
    if (c.focus === "sub") return "sub-clip";
  }
  return c.format;
}

/** "Max Holloway vs Justin Gaethje" or "Alex Pereira · Knockout highlights". */
export function clipMatchup(c: Clip): string {
  return isReel(c) ? `${c.fighters[0]} · ${clipLabel(c)}` : `${c.fighters[0]} vs ${c.fighters[1]}`;
}

/** "UFC 300 · 2024", "UFC 300", "2024" or "". */
export function clipEventLine(c: Clip): string {
  return [c.event, c.year != null && !c.event.includes(String(c.year)) ? String(c.year) : ""].filter(Boolean).join(" · ");
}

/** Big word for the centre badge: KO, TKO, SUB, DEC, or VS. */
export function clipResultWord(c: Clip): string {
  if (c.format === "full-fight" || isReel(c)) return "VS";
  const m = (c.method ?? "").toUpperCase();
  if (m.startsWith("TKO") || m.includes("TECHNICAL KNOCKOUT")) return "TKO";
  if (m.startsWith("KO") || m.includes("KNOCKOUT")) return "KO";
  if (m.includes("SUB")) return "SUB";
  if (m.startsWith("DEC")) return "DEC";
  if (c.format === "ko-clip") return "KO";
  if (c.format === "sub-clip") return "SUB";
  return "VS";
}

/** "Flying knee · R1 0:05" from "KO (flying knee), R1 0:05"; the raw method otherwise. */
export function clipFinishLine(c: Clip): string {
  const m = c.method ?? "";
  const how = m.match(/\(([^)]+)\)/)?.[1];
  const when = m.match(/R\d[^,]*$/)?.[0];
  if (how && when) return `${how.charAt(0).toUpperCase()}${how.slice(1)} · ${when}`;
  return m;
}

/** "KO, R1 0:05" from "KO (flying knee), R1 0:05". */
export function clipMethodShort(c: Clip): string {
  return (c.method ?? "").replace(/\s*\([^)]*\)/, "").trim();
}

/** Lower-cased, accent-free text used by search. */
export function clipSearchText(c: Clip): string {
  return normalizeClipName([...c.fighters, c.event, c.year ?? "", c.division ?? "", clipLabel(c), c.title, c.channel].join(" "));
}

/** Sort key: newest first, undated items last (by year when known). */
export function clipTime(c: Clip): number {
  if (c.date) return Date.parse(c.date + "T12:00:00Z");
  if (c.year != null) return Date.UTC(c.year, 6, 1);
  return -Infinity;
}

export const clipIsVertical = (c: Clip) => c.width != null && c.height != null && c.height > c.width;

export function clipEmbedUrl(c: Clip): string {
  const start = c.start != null ? `&start=${c.start}` : "";
  return `https://www.youtube-nocookie.com/embed/${c.id}?autoplay=1&rel=0&modestbranding=1&playsinline=1${start}`;
}

/** YouTube's own thumbnail (embed hosts only; blocked by the artifact CSP). */
export function clipThumb(c: Clip, size: "hq" | "maxres" = "hq"): string {
  return `https://i.ytimg.com/vi/${c.id}/${size === "maxres" ? "maxresdefault" : "hqdefault"}.jpg`;
}

export function clipWatchUrl(c: Clip): string {
  const start = c.start != null ? `&t=${c.start}s` : "";
  return `https://www.youtube.com/watch?v=${c.id}${start}`;
}

/* ---------- where can clips play? ---------- */

/**
 * "embed": YouTube iframes work (GitHub Pages, local dev).
 * "link":  the host blocks third-party frames and images (the claude.ai artifact frame and anything
 *          unknown), so clips are designed cards that open YouTube in a new tab via real links.
 */
export type ClipMode = "embed" | "link";

// The app rewrites the query string on its first render, and this module is usually loaded lazily
// after that, so fall back to the URL the page was originally navigated to.
function readClipModeFlag(): string | null {
  if (typeof window === "undefined") return null;
  const now = new URLSearchParams(window.location.search).get("clipmode");
  if (now) return now;
  try {
    const nav = performance.getEntriesByType?.("navigation")[0] as PerformanceNavigationTiming | undefined;
    return nav?.name ? new URL(nav.name).searchParams.get("clipmode") : null;
  } catch {
    return null;
  }
}
const clipModeFlag = readClipModeFlag();

export function detectClipMode(): ClipMode {
  if (clipModeFlag === "link" || clipModeFlag === "embed") return clipModeFlag;
  if (typeof window === "undefined") return "link";
  const h = window.location.hostname.toLowerCase();
  return h.endsWith("github.io") || h === "localhost" || h === "127.0.0.1" ? "embed" : "link";
}

/* ---------- portraits (own images only; no external hosts) ---------- */

type PortraitMaps = { seed: Map<string, string>; champ: Map<string, string> };
let maps: PortraitMaps | null = null;

function portraitMaps(): PortraitMaps {
  if (maps) return maps;
  const seedMap = new Map<string, string>();
  const champ = new Map<string, string>();
  for (const f of Object.values(SEED_FIGHTERS)) {
    if (f.name && f.image) {
      seedMap.set(normalizeClipName(f.name), f.image);
      seedMap.set(tokenSorted(f.name), f.image);
    }
  }
  for (const d of DIVISIONS) {
    const ch = d.champion as { name?: string; img?: string } | undefined;
    if (ch?.name && ch.img) {
      champ.set(normalizeClipName(ch.name), ch.img);
      champ.set(tokenSorted(ch.name), ch.img);
    }
  }
  maps = { seed: seedMap, champ };
  return maps;
}

/** Our own bundled portrait for a fighter (seed portrait, else champion cut-out), or null. */
export function clipPortrait(name: string): string | null {
  if (!normalizeClipName(name)) return null;
  const m = portraitMaps();
  const k = normalizeClipName(name), t = tokenSorted(name);
  return m.seed.get(k) ?? m.seed.get(t) ?? m.champ.get(k) ?? m.champ.get(t) ?? null;
}

/** Roster slug whose (lazily loaded) photo can stand in when there is no bundled portrait. */
export function clipRosterSlug(name: string): string | null {
  const slugs = slugsForName(name);
  return slugs.length === 1 ? slugs[0] : null;
}
