// AUTO-GENERATED by scripts/index-ledger.mjs — do not edit by hand.
import type { Ledger } from "./ledger-types";
import l0 from "../data/ledger/dwcs-2026-week1.json";
import l1 from "../data/ledger/dwcs-2026-week10.json";
import l2 from "../data/ledger/dwcs-2026-week2.json";
import l3 from "../data/ledger/dwcs-2026-week3.json";
import l4 from "../data/ledger/dwcs-2026-week4.json";
import l5 from "../data/ledger/dwcs-2026-week5.json";
import l6 from "../data/ledger/dwcs-2026-week6.json";
import l7 from "../data/ledger/dwcs-2026-week7.json";
import l8 from "../data/ledger/dwcs-2026-week8.json";
import l9 from "../data/ledger/dwcs-2026-week9.json";
import l10 from "../data/ledger/noche-2026.json";
import l11 from "../data/ledger/pfl-chicago2.json";
import l12 from "../data/ledger/ufc-fn-289.json";
import l13 from "../data/ledger/ufc331.json";
import l14 from "../data/ledger/ufc332.json";
import l15 from "../data/ledger/ufc333.json";
export const LEDGERS = [l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15] as unknown as Ledger[];
