import type {Event,Fight} from './types';
export type TechnicalContext={fighters:string[];assessment:string;implication:string;evidence:{fighter:string;date:string;note:string;url:string}[];limitation:string};
// Original fight reporting read September 15, 2026. No odds or author winner picks.
// Qualitative interpretation stays visible alongside the immutable statistics model.
export const TECHNICAL_CONTEXT:TechnicalContext[]=[
 {fighters:['joshua-van','alexandre-pantoja'],assessment:'Van lean, with a serious back-control threat',implication:'Van’s escapes and late output support his statistical lean. Pantoja’s ability to turn a scramble into back control is the clearest reason to keep confidence modest; an escape against Taira does not guarantee an escape here.',evidence:[
  {fighter:'Joshua Van',date:'2026-05-09',note:'Against Taira, he repeatedly returned to his feet after takedowns and attacked the body and head late. Taira still reached dominant positions, including mount.',url:'https://www.mmafighting.com/ufc/487344/ufc-328-video-joshua-van-dazzles-with-late-knockout-to-finish-tatsuro-taira-after-back-and-forth-war'},
  {fighter:'Alexandre Pantoja',date:'2024-12-07',note:'Against Asakura, he kept pressuring after striking exchanges and a defended takedown. A second-round scramble led to the back and a choke.',url:'https://www.mmafighting.com/2024/12/8/24315957/alexandre-pantoja-vs-kai-asakura-full-fight-video-highlights-ufc-310'}],limitation:'Two different opponents; Pantoja evidence is older. Their injury-shortened first meeting does not establish a normal striking advantage. Reports read; video not watched.'},
 {fighters:['arman-tsarukyan','mauricio-ruffy'],assessment:'The wrestling route strengthens the Tsarukyan lean',implication:'Repeated entries and top pressure are a concrete way to attack the vulnerability Ruffy showed against Saint Denis. This supports Tsarukyan without assuming every takedown becomes a finish.',evidence:[
  {fighter:'Arman Tsarukyan',date:'2024-04-13',note:'Against Oliveira, he reversed out of bottom position, worked cage takedowns and landed ground strikes. Oliveira also threatened a guillotine and a late D’Arce.',url:'https://www.mmafighting.com/2024/4/13/24129790/ufc-300-results-arman-tsarukyan-wins-split-decision-over-charles-oliveira-in-back-and-forth-battle'},
  {fighter:'Mauricio Ruffy',date:'2025-09-06',note:'Saint Denis repeatedly forced grappling exchanges and eventually took his back for a second-round submission. Ruffy had brief success when striking space opened.',url:'https://www.mmafighting.com/ufc/402705/ufc-paris-results-benoit-saint-denis-snags-face-crank-submission-of-mauricio-ruffy'}],limitation:'Historical examples, not proof of current camp preparation. Ruffy may have improved; Tsarukyan also exposed his neck in transitions. Reports read; video not watched.'},
 {fighters:['tai-tuivasa','robelis-despaigne'],assessment:'Tuivasa’s route is much less secure than the raw résumé suggests',implication:'Repeated ground-control losses are a genuine warning. They do not automatically transfer to a primarily striking matchup: Despaigne still has to demonstrate the relevant approach. Keep this disagreement visible rather than treating a larger physique as proof of an easy win.',evidence:[
  {fighter:'Tai Tuivasa',date:'2026-01-31',note:'Teixeira controlled early rounds with takedowns and top pressure. Tuivasa threatened a late comeback after Teixeira tired, but could not complete it.',url:'https://www.mmafighting.com/ufc/469266/ufc-325-results-tallison-teixeira-survives-late-comeback-attempt-from-tai-tuivasa-to-win-decision'}],limitation:'Only one side has technical reporting reviewed here. No film-adjusted winner or confidence percentage is asserted.'},
 {fighters:['patricio-pitbull','dooho-choi'],assessment:'A recent defensive warning for Pitbull',implication:'The Pico performance is a reason to question how comfortably Pitbull handles sustained straight punching. It supports caution around his old résumé, but does not by itself prove Choi will reproduce Pico’s performance.',evidence:[
  {fighter:'Patricio Pitbull',date:'2026-04-11',note:'Pitbull reported orbital and nasal fractures from early straight punches against Pico and said impaired vision left him defending for much of round two.',url:'https://www.mmafighting.com/ufc/482812/patricio-pitbull-lost-my-vision-during-ufc-327-fight-with-aaron-pico-after-fracturing-orbital-bone-nose'}],limitation:'This is an attributed fighter account, not a current injury assessment. Choi’s official Santos clip was located; no fight frames were reviewed.'}
];
export function technicalContext(event:Event,fight:Fight){if(event.promotion!=='UFC'||!/^UFC\s+\d+/.test(event.title))return null;const item=TECHNICAL_CONTEXT.find(x=>x.fighters.includes(fight.a)&&x.fighters.includes(fight.b));return item&&item.evidence.every(e=>e.date<event.date)?item:null;}
