/**
 * Build lib/stats-timeline.json: one compact UFC stat row per bout for every seed fighter,
 * from public/roster/roster.json (UFCStats per-fight totals). The engine turns these into
 * "as of" striking/grappling rates using only bouts strictly before each event (lib/fight-stats.ts).
 *
 * Also builds (engine v1.3):
 *  - lib/round-timeline.json   one round-by-round summary row per UFC bout for every seed fighter, from
 *                              public/roster/rounds.json (lib/round-features.ts; compact SHIPPED_FIELDS only)
 *  - data/scouting-auto.json   machine-generated scouting tags from those rows (source "ufcstats-rounds"),
 *                              kept apart from the human notes in data/scouting.json
 *
 * Run after the roster is rebuilt:  npx tsx scripts/build-stats-timeline.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { SEED_FIGHTERS } from "../lib/data";
import { sameFighter } from "../lib/ledger";
import type { StatRow } from "../lib/fight-stats";
import { compactRow, roundRowsFromRoster, SHIPPED_FIELDS, type RoundRow, type RoundsDoc, type WithRounds } from "../lib/round-features";
import { autoScoutNotes, type AutoNote } from "../lib/scouting-auto";

type RosterRow = { date: string; opponent: string; result: string; method: string; round: number; time: string; fightId: string; s?: Record<string, number> };
type RosterFighter = { slug: string; name: string; dob: string | null; history: RosterRow[] };
const roster = JSON.parse(readFileSync("public/roster/roster.json", "utf8")) as { asOf: string; source: string; fighters: RosterFighter[] };
const bySlug = new Map(roster.fighters.map((f) => [f.slug, f]));
const norm = (s: string) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z]/g, "");

export function toStatRows(r: RosterFighter): StatRow[] {
  return r.history
    .filter((h) => h.s && h.s.sec > 0)
    .map((h) => {
      const s = h.s!;
      return [h.date, s.sec, s.sl, s.osl, s.tdl, s.tda, s.otdl, s.otda, s.kd, s.okd, s.ctrl, s.octrl, s.sub, s.sa, s.osa] as StatRow;
    });
}

let roundsDoc: RoundsDoc | null = null;
try { roundsDoc = JSON.parse(readFileSync("public/roster/rounds.json", "utf8")) as RoundsDoc; } catch { console.warn("public/roster/rounds.json missing: run python3 scripts/build-roster.py first (round timeline left empty)"); }
const out: Record<string, { dob?: string; rows: StatRow[] }> = {};
const roundOut: Record<string, RoundRow[]> = {};
const auto: { fighter: string; name: string; tags: string[]; notes: Omit<AutoNote, "source">[] }[] = [];
const dayAfter = new Date(Date.parse(roster.asOf) + 86400000).toISOString().slice(0, 10);
let matched = 0, skipped = 0;
for (const f of Object.values(SEED_FIGHTERS)) {
  const ufcDates = new Set(f.history.filter((h) => h.promotion === "UFC").map((h) => h.date));
  const candidates = [bySlug.get(f.id), ...roster.fighters.filter((r) => norm(r.name) === norm(f.name))].filter(
    (r, i, xs): r is RosterFighter => !!r && xs.indexOf(r) === i && sameFighter(r.name, f.name),
  );
  // Namesakes (Bruno Silva, Jean Silva…): demand at least one UFC bout date the seed agrees with.
  const agree = candidates.filter((r) => r.history.some((h) => ufcDates.has(h.date)));
  const pick = agree.length === 1 ? agree[0] : !ufcDates.size && candidates.length === 1 ? candidates[0] : null;
  if (!pick) {
    if (candidates.length) skipped++;
    continue;
  }
  const rows = toStatRows(pick);
  if (roundsDoc) {
    const rr = roundRowsFromRoster(pick.slug, pick.history, roundsDoc);
    if (rr.length) {
      roundOut[f.id] = rr.map(compactRow);
      const notes = autoScoutNotes({ ...f, roundTimeline: rr } as WithRounds, dayAfter);
      if (notes.length) auto.push({ fighter: f.id, name: f.name, tags: notes.map((n) => n.tag), notes: notes.map(({ source: _s, ...n }) => n) });
    }
  }
  if (!rows.length && !pick.dob) continue;
  out[f.id] = { ...(pick.dob ? { dob: pick.dob } : {}), rows };
  matched++;
}
const doc = { asOf: roster.asOf, source: "UFCStats per-fight totals via public/roster/roster.json (scripts/build-stats-timeline.ts)", fighters: out };
writeFileSync("lib/stats-timeline.json", JSON.stringify(doc) + "\n");
writeFileSync(
  "lib/round-timeline.json",
  JSON.stringify({ asOf: roster.asOf, source: "UFCStats round-by-round via public/roster/rounds.json (scripts/build-stats-timeline.ts)", fields: SHIPPED_FIELDS, fighters: roundOut }) + "\n",
);
auto.sort((a, b) => a.fighter.localeCompare(b.fighter));
writeFileSync(
  "data/scouting-auto.json",
  JSON.stringify(
    {
      asOf: roster.asOf,
      source: "ufcstats-rounds",
      generated: "MACHINE-GENERATED by scripts/build-stats-timeline.ts from UFCStats round-by-round numbers (lib/scouting-auto.ts). Suggestions only: not human film study, not read by the engine, never merged into data/scouting.json.",
      fighters: auto,
    },
    null,
    1,
  ) + "\n",
);
console.log(`round timeline: ${Object.keys(roundOut).length} seed fighters, ${Object.values(roundOut).reduce((s, x) => s + x.length, 0)} bout rows · auto-scouting: ${auto.length} fighters tagged (${auto.reduce((s, a) => s + a.tags.length, 0)} tags)`);
console.log(`stats timeline: ${matched} seed fighters matched, ${skipped} ambiguous skipped, ${Object.values(out).reduce((s, x) => s + x.rows.length, 0)} bout rows`);
