// Regenerates lib/ledger-index.ts from data/ledger/*.json. Run after adding a ledger file.
import { readdirSync, writeFileSync } from "node:fs";
const files = readdirSync("data/ledger").filter((f) => f.endsWith(".json")).sort();
const ids = files.map((f, i) => [`l${i}`, f]);
writeFileSync("lib/ledger-index.ts",
`// AUTO-GENERATED by scripts/index-ledger.mjs — do not edit by hand.
import type { Ledger } from "./ledger-types";
${ids.map(([v, f]) => `import ${v} from "../data/ledger/${f}";`).join("\n")}
export const LEDGERS = [${ids.map(([v]) => v).join(", ")}] as unknown as Ledger[];
`);
console.log(`indexed ${files.length} ledger files`);
